apiVersion: v1
kind: ConfigMap
metadata:
  name: slotify-config
  namespace: slotify
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/slotifydb
  SPRING_DATASOURCE_USERNAME: slotify
  SPRING_DATASOURCE_PASSWORD: slotify123
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SERVER_PORT: "8080"